---
# Quick checks to make before spending time on test and package.clone:
# on failure -> failed-pre-checks pipeline
# on success --> cargo-test (parallel) ---> [ test-package-success | test-package-failure ]
#            \-> package  (parallel) ----/
kind: pipeline
type: docker
name: pre-checks

# Steps perform as fast serially, due to file thrashing.
steps:
  - name: cargo-fmt
    image: casperlabs/node-build-u1804
    commands:
      - rustup component add rustfmt
      - cargo fmt --all -- --check

  - name: cargo-clippy
    image: casperlabs/node-build-u1804
    environment:
      RUSTFLAGS: '-D warnings'
    commands:
      - make setup-rs
      - rustup component add clippy
      - cargo clippy --all-targets --all-features --workspace

  - name: cargo-audit
    image: casperlabs/node-build-u1804
    commands:
      - cargo install cargo-audit
      - cargo generate-lockfile
      - cargo audit

trigger:
  branch:
    - master
    - trying
    - staging
    - dev
    - "release-*"
    - "feat-*"
  event:
    exclude:
      - tag

---
# Packaging pipeline, runs in parallel with cargo-test pipeline
kind: pipeline
type: docker
name: package

steps:
- name: nctl-upgrade-test
  image: casperlabs/node-build-u1804
  environment:
    AWS_ACCESS_KEY_ID:
      from_secret: put-drone-aws-ak
    AWS_SECRET_ACCESS_KEY:
      from_secret: put-drone-aws-sk
  commands:
    - "bash -i ./ci/nctl_upgrade.sh"
  when:
    branch:
      - trying
      - staging

depends_on:
  - pre-checks

trigger:
  branch:
    - master
    - trying
    - staging
    - dev
    - "release-*"
    - "feat-*"
  event:
    exclude:
      - tag

volumes:
- name: nctl-temp-dir
  temp: {}
