---
# Quick checks to make before spending time on test and package.clone:
# on failure -> failed-pre-checks pipeline
# on success --> cargo-test (parallel) ---> [ test-package-success | test-package-failure ]
#            \-> package  (parallel) ----/
kind: pipeline
type: docker
name: pre-checks

# Steps perform as fast serially, due to file thrashing.
steps:
  - name: cargo-fmt
    image: casperlabs/node-build-u1804
    commands:
      - rustup component add rustfmt
      - cargo fmt --all -- --check

  - name: cargo-clippy
    image: casperlabs/node-build-u1804
    environment:
      RUSTFLAGS: '-D warnings'
    commands:
      - make setup-rs
      - rustup component add clippy
      - cargo clippy --all-targets --all-features --workspace

  - name: cargo-audit
    image: casperlabs/node-build-u1804
    commands:
      - cargo install cargo-audit
      - cargo generate-lockfile
      - cargo audit

trigger:
  branch:
    - master
    - trying
    - staging
    - dev
    - "release-*"
    - "feat-*"
  event:
    exclude:
      - tag

---
# Packaging pipeline, runs in parallel with cargo-test pipeline
kind: pipeline
type: docker
name: package

steps:
- name: nctl-upgrade-assets-stage-rc
  image: casperlabs/node-build-u1804
  commands:
    - "./ci/nctl_upgrade_stage.sh"
  volumes:
  - name: tmp_dir
    path: /tmp/nctl_upgrade_stage
  when:
    branch:
      - "release-*"
    event:
      - push

- name: nctl-bucket-upload-rc
  image: plugins/s3-sync:latest
  settings:
    bucket: 'nctl.casperlabs.io'
    access_key:
      from_secret: put-drone-aws-ak
    secret_key:
      from_secret: put-drone-aws-sk
    region: us-east-2
    source: '/tmp/nctl_upgrade_stage/'
    target: "/${DRONE_BRANCH}/"
  volumes:
  - name: tmp_dir
    path: /tmp/nctl_upgrade_stage
  when:
    branch:
      - "release-*"
    event:
      - push

depends_on:
  - pre-checks

trigger:
  branch:
    - master
    - trying
    - staging
    - dev
    - "release-*"
    - "feat-*"
  event:
    exclude:
      - tag

volumes:
- name: tmp_dir
  temp: {}

---
# act on release - when the tag is created
kind: pipeline
type: docker
name: release-by-tag

steps:
- name: nctl-upgrade-assets-stage
  image: casperlabs/node-build-u1804
  commands:
    - "./ci/nctl_upgrade_stage.sh"
  volumes:
  - name: tmp_dir
    path: /tmp/nctl_upgrade_stage

- name: nctl-bucket-upload
  image: plugins/s3-sync:latest
  settings:
    bucket: 'nctl.casperlabs.io'
    access_key:
      from_secret: put-drone-aws-ak
    secret_key:
      from_secret: put-drone-aws-sk
    region: us-east-2
    source: '/tmp/nctl_upgrade_stage/'
    target: "/${DRONE_TAG}/"
  volumes:
  - name: tmp_dir
    path: /tmp/nctl_upgrade_stage

volumes:
- name: tmp_dir
  temp: {}

trigger:
  ref:
  - refs/tags/v*
